spring:
  datasource:
    url: jdbc:${DATABASE}://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DIALECT}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DIALECT}
  profiles:
    active: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    filter: true
    tagsSorter: alpha
server:
  port: 9090

sendinblue:
  mail:
    api_key: ${sendinblue_api}
    url: ${sendinblue_mail}

app:
  name: ${app_name}
  email: ${app_email}

admin:
  full_name: ${admin_name}
  email: ${admin_email}
  password: ${admin_password}
#  phone_number: ${admin_phone_number}

access_expiration: ${access_token}
refresh_expiration: ${refresh_token}

private_key: ${private}
public_key: ${public}
base_url: ${url}


Jwt_Secret_Key: ${SECRET_KEY}

MTN_UNIQUE_CODE: ${MTN}
GLO_UNIQUE_CODE: ${GLO}
AIRTEL_UNIQUE_CODE: ${AIRTEL}
ETISALAT_UNIQUE_CODE: ${ETISALAT}
